### ISSUE TITLE
Subtlety: Consider adding a description for each section in the CSS.

### ISSUE THREAD

**Issue by josephtkim** [hollis96/tea-cozy#4]
At a glance it might be difficult to know which sections of the webpage are being selected in the CSS, so it might be a good idea to add descriptions. Like so:

```css
/* Contact Section */
#contact {
  height: 200px;
}

/* Footer Section */
footer {
  text-align: left;
  padding-left: 20px;
}
```
